name: 图书
icon: /icons/type/Book.svg
children:
  - name: 京东读书
    icon: /icons/京东读书.svg
    url: https://ebooks.jd.com/
  - name: Z-Library
    icon: /icons/Z-Library.png
    url: https://z-lib.io/
    background: transparent
  - name: 安娜的档案
    icon: /icons/安娜的档案.png
    url: https://zh.annas-archive.org/
    background: transparent
  - name: iReader
    icon: /icons/iReader.svg
    url: http://192.168.31.202:10123/
    background: transparent
